### PR TITLE
Synchronize content of html_DATA with doc folder

### PR DESCRIPTION
**Pull request by bagong**
I've added and removed files from html_DATA to allow "install" to succeed. Also reordered the list alphabetically to allow for easier comparison.

### CODE REVIEW

**Review by evpobr — APPROVED** [review]
Thanks @bagong , it really seems like that. I've created issue erikd/libsndfile#201, now waiting what @erikd thinks about it.

**Comment by bagong** [comment]
Sure! This is exciting. I am just going through the VS2015 build to see how useable it is already. I'll be linking dynamically to SuperCollider for now, and also check whether FLAC/Vorbis/Ogg can be used in this constellation. This is a very nice contribution for us, as SuperCollider will have to move to VS on Windows in the nearer future, and we have a midterm plan of enhancing audio-file type support by cleaning up how we link to libsndfile. It has become quite a mess on our side over the time.

**Comment by erikd** [comment]
The doc listed in `doc/Makefile.am` should be considered the "correct" list. I see no good reason to add `linux_games_programming.txt`.

**Comment by bagong** [comment]
Done and added print.css as suggested in other thread. But don't worry about this. I was just trying go get install to work locally and thought, while I am at it I might as well... Feel free to close.

**Comment by evpobr** [comment]
@bagong , can you reset my fa76146 and rebase your pull request?

**Comment by bagong** [comment]
Haha, that's expecting too much git foo from me ;) Let's just close. I thought this could be a time saver, but it's a work creator ;). And there is a typo in the adjustment I made. Sorry for the noise.

**Comment by evpobr** [comment]
@bagong , what typo?

**Comment by bagong** [comment]
When I adjusted to Makefile.am, I forgot to add the subfolder doc/ in front of the filenames ;). It's in there right now, I added them and force pushed. But that's not good style and your merge from master is gone... To return it to the state you created is too difficult for me ;). It's certainly not worth the sweat, as the actual change will only take you 2 mins ;)

**Comment by evpobr** [comment]
@bagong , OK, i will do it.

**Comment by evpobr** [comment]
Merged via ed576c9.

**Pull request closed without merging**
